### ISSUE TITLE
Simple output

### ISSUE THREAD

**Issue by NoahTheDuke** [donut-party/dbxray#7]
I really like `schema.rb` as a documentation method and want to use dbxray as a way to replicate it. The current output of dbxray is extremely detailed and verbose (specifically the `:raw` part of each entry).

I would like to get a less detailed output somehow, one that retains the basics (column name and type and uniqueness and defaults etc), and maybe puts foreign keys or indexes or constraints in a single line or a two entry map (which columns, title).

Thank you so much, this tool is very very cool.

**Comment by flyingmachine** [comment]
This is a great suggestion! I will find a way to work it in.

**Comment by flyingmachine** [comment]
OK, I've added an `:include-raw?` option so that the raw output is opt-in. How's that work for you?

**Comment by NoahTheDuke** [comment]
Looking great! I think there are some ways to make it work better for my use-case but I can do that with normal Clojure function-writing.

**Comment by flyingmachine** [comment]
awesome! but also feel free to share your ideas, the library's very alpha so I love hearing what folks would like to see
