### ISSUE TITLE
unconnected-tables tries to run set/difference between a set and a con?

### ISSUE THREAD

**Issue by Trisk3lion** [donut-party/dbxray#8]
Hello!

Really cool package!I have been trying it out with DB2 and noticed something that maybe is a bug.

When I run dbxray on a table with foreign keys i get and error that `unconnected-tables` tries to do `set/difference` on a Con.
And from some quick debugging that seems to be the case. `table-names` is converted to a set but `connected-tables` is not.

Or am I missing something? :)

**Comment by flyingmachine** [comment]
Dang it, I knew that would come back to bite me! Will get a fix up.

**Comment by flyingmachine** [comment]
ok, I think this is fixed now. Would would you like to give version `0.0.70` a try?

**Comment by Trisk3lion** [comment]
Works perfectly now!
